package main.Absyn; // Java Package generated by the BNF Converter.

public class ATypeId extends Arg {
  public final Type type_;
  public final String id_;
  public ATypeId(Type p1, String p2) { type_ = p1; id_ = p2; }

  public <R,A> R accept(main.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof main.Absyn.ATypeId) {
      main.Absyn.ATypeId x = (main.Absyn.ATypeId)o;
      return this.type_.equals(x.type_) && this.id_.equals(x.id_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.id_.hashCode();
  }


}
