package main.Absyn; // Java Package generated by the BNF Converter.

public class DStm extends Def {
  public final Stm stm_;
  public DStm(Stm p1) { stm_ = p1; }

  public <R,A> R accept(main.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof main.Absyn.DStm) {
      main.Absyn.DStm x = (main.Absyn.DStm)o;
      return this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_.hashCode();
  }


}
