

module AbsCpp where

-- Haskell module generated by the BNF converter




newtype QuaConstId = QuaConstId String
  deriving (Eq, Ord, Show, Read)
data Program = PDefs [Def]
  deriving (Eq, Ord, Show, Read)

data Def
    = DFunStm Type Id [Arg] [Stm]
    | DFun Type Id [Arg]
    | DDecl Stm
    | DUsing Id
  deriving (Eq, Ord, Show, Read)

data Arg
    = AType Type
    | ATypeConst Type
    | ATypeId Type Id
    | AExp Type Id Exp
    | AConst Type Id
  deriving (Eq, Ord, Show, Read)

data Decl = Decl Id | DeclExp Id Exp
  deriving (Eq, Ord, Show, Read)

data Stm
    = SDeclConst Type [Decl]
    | STypedef Type Id
    | SDecl Type [Decl]
    | SExp Exp
    | SReturn Exp
    | SWhile Exp Stm
    | SDoWhile Stm Exp Stm
    | SFor Stm Exp Exp Stm
    | SIf Exp Stm
    | SIfElse Exp Stm Stm
    | SBlock [Stm]
    | SEnd
  deriving (Eq, Ord, Show, Read)

data Associative = PFun [Exp] | PIndex Exp
  deriving (Eq, Ord, Show, Read)

data Type
    = TAddr Type | TBool | TDouble | TInt | TVoid | TChar | TId Id
  deriving (Eq, Ord, Show, Read)

data Id = IId [QuaConstId]
  deriving (Eq, Ord, Show, Read)

data Exp
    = EInt Integer
    | EDouble Double
    | EString [String]
    | EChar Char
    | ETrue
    | EFalse
    | EId Id
    | ECall Id [Associative]
    | EStut Exp Exp
    | EPro Exp Exp
    | EPIncr Exp
    | EPDecr Exp
    | EIncr Exp
    | EDecr Exp
    | EDere Exp
    | ENege Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EMod Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | ELShift Exp Exp
    | ERShift Exp Exp
    | ELt Exp Exp
    | EGt Exp Exp
    | ELEq Exp Exp
    | EGEq Exp Exp
    | EEq Exp Exp
    | ENEq Exp Exp
    | EAnd Exp Exp
    | EOr Exp Exp
    | EAss Exp Exp
    | EAssDec Exp Exp
    | EAssInc Exp Exp
    | ECond Exp Exp Exp
    | EThrow Exp
  deriving (Eq, Ord, Show, Read)

